-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aluno
(
    idaluno integer NOT NULL,
    CONSTRAINT aluno_pkey PRIMARY KEY (idaluno)
);

CREATE TABLE IF NOT EXISTS public.matriculado
(
    aluno_idaluno integer,
    disciplina_iddisciplina integer
);

CREATE TABLE IF NOT EXISTS public.disciplina
(
    iddisciplina integer NOT NULL,
    professor_idprofessor integer,
    CONSTRAINT disciplina_pkey PRIMARY KEY (iddisciplina)
);

CREATE TABLE IF NOT EXISTS public.professor
(
    idprofessor integer NOT NULL,
    departamento_iddepartamento integer,
    CONSTRAINT professor_pkey PRIMARY KEY (idprofessor)
);

CREATE TABLE IF NOT EXISTS public.departamento
(
    iddepartamento integer NOT NULL,
    nome_departamento character varying(45) COLLATE pg_catalog."default",
    campus character varying(45) COLLATE pg_catalog."default",
    idprofessor_coordenador integer,
    CONSTRAINT departamento_pkey PRIMARY KEY (iddepartamento)
);

CREATE TABLE IF NOT EXISTS public.curso
(
    idcurso integer NOT NULL,
    departamento_iddepartamento integer,
    CONSTRAINT curso_pkey PRIMARY KEY (idcurso)
);

CREATE TABLE IF NOT EXISTS public.disciplina_e_curso
(
    disciplina_iddisciplina integer,
    curso_idcurso integer
);

CREATE TABLE IF NOT EXISTS public.pre_requisitos_disciplinas
(
    idrequisitos integer NOT NULL,
    disciplina_iddisciplina integer,
    requisitos_idrequisitos integer,
    CONSTRAINT pre_requisitos_disciplinas_pkey PRIMARY KEY (idrequisitos)
);

CREATE TABLE IF NOT EXISTS public.pre_requisitos
(
    idrequisitos integer NOT NULL,
    CONSTRAINT pre_requisitos_pkey PRIMARY KEY (idrequisitos)
);

ALTER TABLE IF EXISTS public.matriculado
    ADD CONSTRAINT matriculado_aluno_idaluno_fkey FOREIGN KEY (aluno_idaluno)
    REFERENCES public.aluno (idaluno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.matriculado
    ADD CONSTRAINT matriculado_disciplina_iddisciplina_fkey FOREIGN KEY (disciplina_iddisciplina)
    REFERENCES public.disciplina (iddisciplina) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.disciplina
    ADD CONSTRAINT disciplina_professor_idprofessor_fkey FOREIGN KEY (professor_idprofessor)
    REFERENCES public.professor (idprofessor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.professor
    ADD CONSTRAINT professor_departamento_iddepartamento_fkey FOREIGN KEY (departamento_iddepartamento)
    REFERENCES public.departamento (iddepartamento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.departamento
    ADD CONSTRAINT departamento_idprofessor_coordenador_fkey FOREIGN KEY (idprofessor_coordenador)
    REFERENCES public.professor (idprofessor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.curso
    ADD CONSTRAINT curso_departamento_iddepartamento_fkey FOREIGN KEY (departamento_iddepartamento)
    REFERENCES public.departamento (iddepartamento) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.disciplina_e_curso
    ADD CONSTRAINT disciplina_e_curso_curso_idcurso_fkey FOREIGN KEY (curso_idcurso)
    REFERENCES public.curso (idcurso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.disciplina_e_curso
    ADD CONSTRAINT disciplina_e_curso_disciplina_iddisciplina_fkey FOREIGN KEY (disciplina_iddisciplina)
    REFERENCES public.disciplina (iddisciplina) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pre_requisitos_disciplinas
    ADD CONSTRAINT pre_requisitos_disciplinas_disciplina_iddisciplina_fkey FOREIGN KEY (disciplina_iddisciplina)
    REFERENCES public.disciplina (iddisciplina) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pre_requisitos_disciplinas
    ADD CONSTRAINT pre_requisitos_disciplinas_requisitos_idrequisitos_fkey FOREIGN KEY (requisitos_idrequisitos)
    REFERENCES public.pre_requisitos (idrequisitos) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;